name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testReadResult1
      id: testreadresult1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testReadResult1
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE2Test.testReadResult1"
        timeout: 10
        max-score: 3
    - name: testReadResult2
      id: testreadresult2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testReadResult2
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE2Test.testReadResult2"
        timeout: 10
        max-score: 4
    - name: testCatchException
      id: testcatchexception
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testCatchException
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE2Test.testCatchException"
        timeout: 10
        max-score: 7
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTREADRESULT1_RESULTS: "${{steps.testreadresult1.outputs.result}}"
        TESTREADRESULT2_RESULTS: "${{steps.testreadresult2.outputs.result}}"
        TESTCATCHEXCEPTION_RESULTS: "${{steps.testcatchexception.outputs.result}}"
      with:
        runners: testreadresult1,testreadresult2,testcatchexception
